import { ArrowLeft, FileText, Shield, AlertTriangle, CheckCircle, Clock, Database, Lock } from 'lucide-react'
import type { Page } from '../App'

interface Props { onNavigate: (page: Page) => void }

export default function TermsPage({ onNavigate }: Props) {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center gap-4">
        <button onClick={() => onNavigate('home')} className="p-2 rounded-xl hover:bg-gray-100 transition-colors">
          <ArrowLeft className="w-5 h-5 text-gray-600" />
        </button>
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900">Terms & Conditions</h1>
          <p className="text-sm text-gray-500 mt-1">Last updated: August 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="space-y-8">
        {/* Acceptance */}
        <Section icon={<CheckCircle className="w-5 h-5" />} title="1. Acceptance of Terms">
          <p>By accessing and using the HeartGuard ML application ("the Application"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Application.</p>
          <p>This Application is provided as a research and educational tool for heart disease risk prediction using machine learning. It is <strong>not</strong> a medical device or diagnostic tool.</p>
        </Section>

        {/* Purpose */}
        <Section icon={<FileText className="w-5 h-5" />} title="2. Purpose of the Application">
          <p>The HeartGuard ML application is designed for:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Research and educational purposes in machine learning and healthcare</li>
            <li>Demonstrating ML-based risk prediction methodologies</li>
            <li>Academic project evaluation and learning</li>
          </ul>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mt-4">
            <p className="text-sm text-amber-800"><strong>Important:</strong> This Application is NOT intended for clinical diagnosis, medical decision-making, or replacing professional healthcare advice.</p>
          </div>
        </Section>

        {/* Medical Disclaimer */}
        <Section icon={<AlertTriangle className="w-5 h-5 text-amber-500" />} title="3. Medical Disclaimer">
          <p>The predictions and risk assessments provided by this Application are generated by machine learning models trained on research datasets. They are <strong>not medical diagnoses</strong> and should not be treated as such.</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Always consult a qualified healthcare professional for medical advice</li>
            <li>Never use this Application as a substitute for professional medical evaluation</li>
            <li>Seek immediate medical attention for any health concerns</li>
            <li>The model was trained on a limited dataset (303 patients) and may not generalize across all populations</li>
          </ul>
        </Section>

        {/* User Responsibilities */}
        <Section icon={<Shield className="w-5 h-5" />} title="4. User Responsibilities">
          <p>By using this Application, you agree to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Use the Application only for its intended purpose</li>
            <li>Not attempt to reverse engineer or exploit the Application</li>
            <li>Not use the Application for any illegal or unauthorized purpose</li>
            <li>Not transmit harmful code or malware</li>
            <li>Understand that predictions are estimates, not guarantees</li>
          </ul>
        </Section>

        {/* Intellectual Property */}
        <Section icon={<Lock className="w-5 h-5" />} title="5. Intellectual Property">
          <p>This Application and its contents are protected by copyright law. The project was developed by <strong>Souvik Barui</strong> as an academic research project.</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Source code is available under the MIT License</li>
            <li>Research data comes from the UCI Machine Learning Repository (CC BY 4.0)</li>
            <li>Academic references are properly cited</li>
            <li>Third-party libraries retain their respective licenses</li>
          </ul>
        </Section>

        {/* Data Usage */}
        <Section icon={<Database className="w-5 h-5" />} title="6. Data Usage & Privacy">
          <p>This Application processes health-related input data for prediction purposes. Please refer to our <button onClick={() => onNavigate('privacy')} className="text-primary-600 hover:underline font-medium">Privacy Policy</button> for complete details on data handling.</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>No personal information is collected or stored</li>
            <li>Input data is processed in real-time and not persisted</li>
            <li>No data is shared with third parties</li>
            <li>All processing occurs client-side or in the API without logging</li>
          </ul>
        </Section>

        {/* Limitation of Liability */}
        <Section icon={<Shield className="w-5 h-5" />} title="7. Limitation of Liability">
          <p>To the maximum extent permitted by law:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>The Application is provided "as is" without warranties</li>
            <li>We do not guarantee the accuracy of predictions</li>
            <li>We are not liable for any decisions made based on predictions</li>
            <li>We are not responsible for any damages arising from use of the Application</li>
            <li>The Application should not be relied upon for medical decisions</li>
          </ul>
        </Section>

        {/* Changes */}
        <Section icon={<Clock className="w-5 h-5" />} title="8. Changes to Terms">
          <p>We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Continued use of the Application constitutes acceptance of modified terms.</p>
        </Section>

        {/* Contact */}
        <Section icon={<FileText className="w-5 h-5" />} title="9. Contact Information">
          <p>For questions about these Terms, please contact:</p>
          <div className="bg-gray-50 rounded-xl p-4 mt-2">
            <p className="font-semibold text-gray-800">Souvik Barui</p>
            <p className="text-sm text-gray-600">Research & Development</p>
            <p className="text-sm text-gray-600 mt-1">Email: <a href="mailto:projectmakersb@gmail.com" className="text-primary-600 hover:underline">projectmakersb@gmail.com</a></p>
            <p className="text-sm text-gray-600 mt-1">GitHub: <a href="https://github.com/souvikbarui2003" target="_blank" rel="noopener noreferrer" className="text-primary-600 hover:underline">github.com/souvikbarui2003</a></p>
          </div>
        </Section>
      </div>
    </div>
  )
}

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="card">
      <div className="flex items-center gap-2 mb-3">
        <div className="text-primary-600">{icon}</div>
        <h2 className="text-lg font-bold text-gray-900">{title}</h2>
      </div>
      <div className="text-sm text-gray-700 leading-relaxed space-y-2">{children}</div>
    </div>
  )
}
